In [ ]:
import pandas as pd
import requests

airlines_url = "https://en.wikipedia.org/wiki/List_of_airline_codes"

headers = {"User-Agent": "airline-codes-scraper/0.1 (your@email.com)"}
resp = requests.get(airlines_url, headers=headers, timeout=30)
resp.raise_for_status()

In [7]:
from io import StringIO
import pandas as pd

tables = pd.read_html(StringIO(resp.text))
print(len(tables))

1

In [8]:
df_airlines = tables[0]

print(df_airlines.head())

  IATA ICAO                                        Airline  \
0   PR  BOI                                            2GO
1  NaN  EVY        34 Squadron, Royal Australian Air Force
2  NaN  GNL                                    135 Airways
3   1A  NaN                          Amadeus IT Group S.A.
4   1B  NaN  Sabre travel network Asia-Pacific (ex-Abacus)

  Telephony Designator Country/Region  \
0                ABAIR    Philippines
1             Multiple            NaN
2              GENERAL  United States
3                  NaN         Global
4                  NaN           APAC

                                   Comments
0                                       NaN
1                                       NaN
2                                       NaN
3  GDS and airline hosting system (CRS/PSS)
4                     Regional distribution

In [ ]:
df_airlines.shape

(6358, 6)

In [14]:
print(df_airlines["IATA"].duplicated().sum())
print(df_airlines["IATA"].isna().sum())

5331
4793

In [ ]:
print(df_airlines["ICAO"].duplicated().sum())
print(df_airlines["ICAO"].isna().sum())

459
116
BOIEVYGNLWYTTFUCHDTTFTWFSECMLAQRTPIUSEKWAZUBEJYHBRODWIGBTAJRSFMAJJXXVBBEABJNKPABGABEMRPAHUFTYAABBDVROHADJABPLTGTTNABXIAENCLACDCYDCFMAROAESBVRBJTCRVORSAXQAVRRRMADCVUEADEDHIADKADWDSCDDSADFTECSWHADRDROADVAXXAAXXTJWSNADDRDDDVNEBSAEEALSAEFDRDFUTMMGAGIWWGAEDAKRRRBCNDARPAEKEPUXPNAJPTKJOWNGHMGLMGUEASRABAUCREAPAJHAOBCRNACRERCBSONVALUEMLLAVXCTDRRODVIFAQAFLPLSAEGAGQARHBJUARJLFTLINPCPALTAHLAPRLDLVSCPSEPSLEAEBTSPRIPVAVMXABUACBAAPAARAASAATAAVAAWAAZABTACEACQACSABSADTADZAFFAFMLBRFLAMACMRYPNKPXGAFNADOACCPNXAVDFSYTTXLMUALNAPNBAHAWGTLBUJXAGMNVDAZBAENNGFWFTASLLYNCCMAHSROOAWFSUPPSOEINEUKVLBFCJTEWSTTLBZHEZUAHRVQASKAEHEROXAUNKYAWPAGAABZROUCNMVREAWLAXYOESASFAVGAZYACXAADSIIBZSAETABMAAFAAMAAOAEAAUAFUBRLAFHBRMAAGAAJAHNAHRAHKAAIACUACVAEAAEQAEYASWASXAMUAMWSEYSFBBRFAFRACGACIVSGAKXALMACMAXEAWIALURSIAGNRUNAFVABNAAQATWABLACHLEPAFSGRLGUYAHOAJXLIBKLAAIMAMIBIEMKGAMGMNETAHANVANZANTAOEAEIAPZAVZAMOAMRAMSAOJAJUAKALIVLJAAGBAGVMVMAMYVGAAOUAPAAPGANAANBNGOTWGNGPSNCSNDSNGSNYAIIBFFBDMBERAPVARXHTTARZASBASCASDAQNARCARRAILAICAIGSPMWOWATJATNATQATSAUXAVNBUBABDAIEAISSBKTHTNMBNSKNTLSGAAFWAELAJMAWNAWTAWWFWIAXBAXDBSBBTIANIANKANEANGABYACALAVMHSAXLAZFAZWMHUMKHAZXRSHATAATCXACVBWATHAMCTGAASJASNASSNPLNPRWAMRSMAWZAAYABBABFABKABOABVACYADATIDADBADGADIADLADNADPADYADQADSADUAEBAECADXAEJAEMAEOAEPAACAAAAEUAEVAEWAEXAEZAFAAFBUTYUVSUVTAFCAFEAFGAFIAFJAFKAFOAFQAFXAFYAFZAGCAGFSLIAGGAGHAGOAGPAGTAGUAGWAGXBLRBLZPLIBMMBNBAGYAGZAHAAHCAHECJEAHFAHGAHHAHPAHWAHYAIAAIBAIHASVAIKAINAIPAIUABQTHMAIRAITAIVBESAIWAIXAIYAIZAJAAJBAJEAJIAJKAJOAJSAJTAJVAJWAJYAKBAKCAKFAKHMNIAKKAKLAKNAKWAKZALBALDALEALFFYSDFAASQALGALLAWETNOTNDTMPALOALPALQALVALWALYALZAMAAMDAMFAMHAMJAMKAMMAMPAMQAMTAMVAMXAMZANCBRPANHANMANOANQANSAOMANWSAPEMSAOAAOCAODAOFAOGMUNMURAOINRONRPAOKAOLAONAOOAOPVIVVIZVJEVGFVERAORSMXAOTAOVAOXAPCSVMAPFAPHAPIAPJPETARFBKLBLAAPLAPMAPOAPPAPQAPUAPWAPXAPYAQAAQLAQOAQTAQUAQZARAARBAREARGARISUNSUOARKARLARMKLDARQARSARTARVARWOSTHUCHUTHUYARYASAASEASGASIASMASOASPASTWAPASZATBATDATEATGATIATKATLATMCPVATPFEOFESFFAFFBATRATTATUATVAUAAUBTUPABWTURTXUTXXAUDAUFAUMAUNAUPSVEAURAUSAUTAUUAUYAVFAVHAVJAVKAVMAVOAVPLFPLFRAVSAVTAVUAVVAVWYRGZAKZZMBGABGDBGFBGGBHCBIVSZAAVYAWBAWKAWOAWRISMAWSAWVAWYAXHAXIAXKAXMXAXWAJIADMWGAXNAXPBNIBNZBOCAXRAXSAXVAYDAYKAYMNPTGBNBJKHHAAYNAYSAYTAYZAZAAZEAZIAZKAZLAZMAZPAZSAZTAZVMHCAZZNARNAUNERNFFOBAOBKOCANFSNGCNGEOULOVAXPEXSSTLROVCRVERVIRVLOVEOVIPTDPTEPLLPLMPSGSLUSCUSIPBMVGUGPXXPYCPVKBASBBTMCYEGFPUEPUTETCXCTVROVRIVEGVVGVLRWILVEJWABVNGVADVMRVLSXAAVUOVTMVUNBOTXPRXLLVAEWHYWDRXECUPAVTYVTAURGVDRVIMWLRURAXLBWLAXFXWAYWGSXAKWPKVABURPWPRURRUSTWLTVLVVMEVVAWLVWTAVNTVZRVIDVXGVXXXAMXAOVAZVASVAMKHVVBCXKXXATCAJCAOCBECBOCBSCBVCCACDACDPCDUCDVCFFCFRCFVCGBCGVCGWCHJCHRCHVCIDCIRCKLCLLCLPCMFCNECNHCNUCNXCPFCRDCRFCRJCRPCRQCTACTECTRCUOCVACWMCWPCYLCYOCYEDAHDAPDBADBDDEFDEGDHLDHMDICDINDJUDLADLSDLUDMCDMIDMLDNADNCDNJDRMDRUDSKDSTEATEAYEBCECEECGECLECMEDAEETEFCEJPELGALXENDENWEOLEOKEOMEPLEPEEQLERGERIERKERMESBESOESUESZETEEVEEVREWE/EWLEXGFACFAGFAJFANFBWFCIFCOFCUFDAFDSFGTFICFIFFIIFIXFJIFLDFLIFLPFLZFMTFNMFNOFNXFPYFRJFRKFRQFRTFSTFTCFXIGAUGBJGCFGCKGFOGGLGGNGHLGHNGILGIPGIZGLLGLTGMEGMMGMSGNTGOAGREGRGGRIGROGRRGRXGSPGSVGTCGTIGTPGUAGVIHADHAHHATHEIHGHHIDHJAHLNHJTHKHHMAHMTHOMHPOHQOHYRHZTICMIFIIKMILKIMEIMNINAINGINOIPLIRDIRHIRWIRXITEITFITIITOIVEIWSJABJADJARJEEJKHUTXJMRJMXJOAJOBJOLJPRJTSJUAJZAKAAKADKAMKAVKEKKFKKFTKGDKHHKIEKKBKKKKLBKLZKORKOYKREKRTKSIKTNKVRKYCKZRLAGLBCLBILBWLDGBOXLDNAKJLDRLEMLETLFALFCLGNLHRLIDLIELKPLKSLKYLLRLMALMLLMPLMTLMXLMYLMZLNKLNTLOKLOULPALPCLPVLROLRWLSKLSMLSRLTILUCLURLVNLVRLXGLXRLYTLZPLZRMAMMAUMBAMBBMBCMBVMCBMCDMCOMDCMDGMDXMEFMFLMGEMGSMIEMLDMLFMLIMLNMMCMMDMMMMMPMMXMNGMOCMOPMORMPDMPXMQTMRLMRMMRTMSCMSKMSMMSOMSVMTBMTEMTKMTYMXOMYSMZKMZLNBKNELNGVNIDNIENIGNKZNRENRSNSONTDNTVNULNVINWGNXAOAOOGIOLVOMGONRONTORPOSNOSOPAJPBTPBUPCGPCKPCSPELPEVPFIPFTPHRPHWPIEPIFPKAPNLPNUPOYPRTPRZPZAQCLQEAQATQKCQLAQSCQUIRADRAIRAPRBERBJRBURBVARURCCRCERCFRCHRCIRCORCPRCQRCURCXRDMREARENRESREUREYRFCRFDRGORGRRGTRHLRIFRISRITRJSRKARLARLKRLLRLNRLZRMDRMERMLRMORMXRNERNMRNRRNVROEROIROLROMRODRPBRPCRRCRRERSCRSORSRRSURTERTHRTORTQRTURUDRUMRVPRVTRWBRWCRWYRXTRWSRZLRZNRZZSBHSCDSCMSDOSDPSEFSERSGVSHHSIYSIZSJNSKPSMISMJSODSOESOGSPDSPJSPOSPYSPZSQRSRISRVSSLSSMSSNSTKSUESUWSUYSVKSYLSYTSZNTAATAOTBLTBOTCITCOTDGTDTTDYTEDTIRTLDTLETLUTMETOCTOHTOKTONTPBTPCTPKTPOTQSTRHTRSTSCTSQTTBTTETUNTWNTXDTXFTXITZATZTUAGUARUCKUGAUEDUKRUMBUNDUSCVNRVTGWASAERAAKAAHAALXFSXMGAANABIDJAEDYSRYXXXABRXJAAAEACPXMEAUZVAIVXPAVEVRTAJFVTTCHPAVAMCJONEGLGXAVAVBAVQACJVSRVLIVSAAZUBBFCFEBRTEFWBACBCFBOBBDRBAEBHSBABBFWBXABJABAJOGJBTCBEFBLNBAALAZBHIPNTBTLBLLBLTBJCBTHCPJEAHBTKBAVAJCAUJCWRBJVBHKBXJBYGBBJBCJBNABTNBAFBAKBALBAMBANBARBAUBAWBAXBAYBBABBCBBDBBSBBVBBWBBZBCIBCLBCRBCTBCVBCYBDABONBDFAYBBEABEDBEHBEKBETBFCBFGBFLBFOBFRBFSBGHBGIBGKBGLBGMBGRBGTBHABHLBHNBHOBHPBHRBHTBHYBIDBIGBIHBILBINBIOBIRBIZBJSBKABKFBKKBKJBKPBKVBLBBLCBLEBLFBLGBLHBLJBLMBLSBLVBMABMRBMDBMEBMHBMIBMJBMLBMNBMWBMXBNDBNEBNFBNGBNJBNLBNRBNSBNTBNVBNWBODBOABOEBOFBOOBOUBPABPKBPOBPSBPTBPXBRBBRDBREBRGBRKBRNBRSBRUBRVBRWBRXBRYBSCBSDBSIBSJBSMBSSBSTBSWBSYBTQBTRBTTBTVBTZBUCBULBUNBUZBVABVCBVNBVTBVUBWDBWGBWIBWLBXHBXIBYABYCBYFBYLBYRBYEBZABZHBZZCBJCKMCLFCLNCXSBELEBAEXBEXPFOSGAAHAWHAXIBBIRJIVRLAJLBYLEDLTLLXJLZBMBRNKFNYBOTAOUFPEBPOIPPSPVORHDRLRRRSSCJSHTSKHTXBUKAVLXVOLWFDWTNXBOXDAXMSZBAJMPBOVBRJMXYCJLLHXSRJTIPORORWGRMUCJZDYNCRCQAICBHCAABKRBFNAWXBBNAIOAIDSMWCCLKMECCBCYHCFBXCAGCYCBICPIICLCMRCTZCCFCEDHBIHEMSCHHKSVCICKCCMZCNTOAPPDRCRHIROCSECTQCBRCVECWDCXECCECGCREZCSLCMVCAVCAMUYCHSOCJAPILCDNCTGHIACFCBZDTKRXNCAKTCPCCDRCWHCWACWWCUIKAPCTOSEMCMYCPXCPDNCPCCICCQEGLCEXCWZVANCWNFVAGOLCDICFHCDMESTGGCMCXCLMCLUCTWCRGCJTCLXICVCGMDELBCBPWDDCCCLTBWAIQQCSXTLCGFICRBCRTCVGKRPCRRULSCMTCSOCSPCPNCSJCAZCBTTEXHDACPACJRCAYCEBCILCEGCECCWECEVCNLCNSCVOCTSCETCAXCTLCNYACNYOGDRNCMACHACEMGLRCQCCSICLWDTVCGSCVCCCVACFCWCURYHAIXADCERIRUCSWCLGCHKCLSCHSOFFCHGCPHCCPNCHCGNCHNWMLCPLCSUCAHHMDCGDCHWHRTCHQCBBCHMCHZCMKCBMCCYCABCVRCYACGOWDYRATCCHDESCADETNCALCKKCESHXACFACTHCAGCBFCNWCHCCYZCSNCXNCUACXHCGUCEPCPWCHFCQNCASOECCHOCHUCIUCIMCINRRUNTSRUSJTIFIVXCXHZXCTVSDRCIXXBGCAQCIICNBHSRCIWCAPCATCIACIVCBAFMCCLKCSFCLYCGKCLZCLDSDJISGCSTTCLCNGCSVCHLOLRCLECJCCAECCXWCOKLRGHPCOMCAWGCMCDECVVCRSCMGFYNCMJCLAKAZMLMCXBCMHCTMCMLCRMCMECMSGARCJSUCACWKCGRCMMCPMGICAIFATFLCTEJVHSEMDRHSSTAVCYFCPZCPSXCOXCSCODCNRCIBCFGCOFCAKCGAROYCCTBSNCACCXOVCHUZAKISXCLCOACMICONCSVCVCKASVYCMPCOPCCWCAICXICRACPBCNCCPGCGYCPTCPRCPOCOOCKEVHTVTECJICRLCOZCOTCHIMGBNSWCIKCSDCUTOUCVLCOWCOYCFDCREELMCANKRMCTNHRZCRXECCCWXCKRCROCRWVCRCTYCYTCUBCTFCBLCTTRGNCYCCYSCYPKYVCEFAHDCSACIECGPHNLKEMJLHFCBCVKCLICHBDJTDPJDJRDLCDLHDNSDRFDMFGDFDDADNKVPADHEVLFDSRRKCDTRENTBDNDSNDETDGODAEDHKDHVDHXJOSRSKDAODAGDHACCDDCSDCXDKADLRKHBDXPDASDSADOPDAFDDLDARDNYDNUDRTDWTDSQDSHGOBDGXDABCVFDSODTNXDTDAUDCODWNDJSDAYDHCIAYDAADKNJDCDWRDEASNOELJDALKMBDLIDSUDNMFECFGCDRYDRXMIZDTYAMBLFODISSPKDRBDGTDIPENADIAXAPDCTSXPDIRDCVOCNDVAXDSDIXDEEUDNFDNIXXDPLADMMYODOADMODVBDONDNVUDCEPADADDORDAVDOMDCADRKDREDUBDBKDUKDBJLPDDUNPHDVVFDUODJEDNLDCEDBRDFSXDYDNRDYEDYABAGDKHEAVISLEBFENYENKELBELNELUEDVMNUEHDEXWEFSEFDFSDEISIAGESIEUYEUJICRFEIEGREFLEGUEAGEGXGYPEGNEESEZXSEGEGJEMDERXHSAEXZEMUECTECJEHAEKCCTKDXHEWAESREAZEAXEALEZEEAQECIGNSLISEMEEPBESJELASGRFYEEJUEZSEZYCMNEJTECQDEINAKECXECDXCCECVEQCECUEDWSLOEDCEDJEIJEUWMSRMSXEGYEJXEMAEIXEIRELYCMXGLQELSESCBRQELXNLKDNDPDVEDOEFGELHEOAMEEVULIEPRSAEAIEJDFGSELTMGGELREAMEFTEMBXSLERUJEMEWWEMTUAESBCEMPCFSMPRETPAUOPRGVNAEEACNIVNEGTVXLTENCENIEGVESEENSEWSESSEKAEQZEQTEQRERHIRYERFEREERTEADEPCESFEEFELLETAETHMJMETDETMEVNECNESNEAKKZEMMZSEBGOJEUPEUUECYEUCECFECAEEZEEUEUGERJJLNRDPEJSELOEMXGEDFPOEUTBCSEAFEBJECBETVEXCEBGESXEWGEWLEVAEVKEVTEIAVTSEVLEWREMNXLAXELGZAEXAVCNEJOVMPLFLEACXAFECSXAHEXKEXUJTREXETRIEXJEJMTEAEXFEXNEXRFXAEICXPLXNALHNXTOLTDXSREPRXROJTMEZJEVSFRXPBRSREFTZFAPFFLEYEIFAFLCFKIDCMFLWFMGFRAFSBLEJFBAFCSFAVFWDFLSFFCFWYFCNFARFAOFAUFBUFVSFJCFAWFEAFDLFAHFRNFATRAFHBLRCKFRWFSWFHLFAYSKMFDRFLLDCNFRMNHKFDXFNKFERHGKFNCFAKFBFFTRFINWBAFNFFIHFFMFABJRFFCCFCAMBLGGAFIRFTSFFRFFPEXVFSXFLEWAFFMRFLNFSHBWYFLRFXYFXTTUDFCKVORFCVFCPFDPFLXCFILTSIVJMITFOIOPTCLBFSLFSUCCKAYRFWQKLOCSKFEXFLTFTLFPSFSRKDZFAZKWXOJYFASFCLFFSTCFFJSFWLFFGFLUEZBFWZVNXFLMEDRFCTFEEFXLFGENVJFJMFJLFILFLYPVV[citation needed]FRBVAWFYAXFABBOBEEFBZFCEFEGGVGGSMFPATORETSINUFYHFCRFYGFGPLILFLKKNENDCFREFOXFTMFVKFMIFKSFOPNOFFOBFORFHSFXCFSAJFYFTEFIAFIEFSCWDSFXRFDOFHYFOMFFFFRLFWCFRGFAFFMYFNYFRRBZYFAEFALFLFFGYFFTITRFTAFNGFUJCFJGAXFAMFFYROGFUNFGLFUAFDBFWKACTFRFFUMFWRGMLDBCGOPHGTGMQKNMGCWGBHGMREXHMTAGGSGBXGBLGCSFFUGCCGENGETGFWGGTGHIGMGGPEGPRGIBBMKGTXGAHGBEGRTGIGGFCGNJSWFGLSGALGXYGASGMAGCHGNRNMLGMJGNFGANGSAAHMGIAGHSEGOGVNGZPGEEGLXGCOGABGDBFGNSWKGWSGNZGTHXGAGMCGNXGSLTGZFGAGGFGFGGAFGAMGNYLGWGERGHYGMIGWIGDNGFDRIVGESGTRGJTGHTGLPGHAGHBNTCRPSGAGDMJGBSGLCBSPGLBGBBGAKGGZGLJNSMSVWGSKGSSXGSXGWGLWGJAGACRLXGOWGJSGGEGOFGOIGLOGDAGDKGAOGDDGPAGRSGLDGOSGAQGLEGOMGONRDRGORHKGGRZHLDGAVGAEGNDCVUGUNLMKGRAGLAGLUGRPGWLGWAHGBHNAGFFGXAGZDHTGGSJGHVGPMEJCTATVMMGMTGSYBSRGIJGNCGIFGEAGIQCGHGUSGUJTSUGUFGFAGATGCNSFYGPCGLFGFSGFTGULGUMGDHGWNAHTETIHSNHAYHCKHTBHAFHRNHYPHFMHOPHLAHWDKTRFMSHAGPOWHHNCHHHLSHAMHTIHRBHNRHTNHTCHBCHAJHKLHLHHCVHHIHJLHMMWVAHGRHGDHANHLXHLFHARHMYNBRPYNHAVHALHKRHMXHKIHZLHVYHVLHBHHDCHCBHCLHHPHLRALJHEBHFRHYHHLMHLIHTPHLUMCMHHEHRAHIFHIGHLKHMCHEACDYHIBHLCCOVHELHCPJKYMVKHAPHAAHNTHENHHHJBAHDRSCOOCEHCYHLPHPLHECHSUHSIHLTHITOFAHTAHTSHLWHEJFHEHLGOAWHMSHACSSHMRXHEDHERHHSHFYHLBHWYHIMHYMHYSHSHHISVMSHGANTHABHHOAHINHOLHCCHTRHMVHASCRKHKCHKEHTUHEXHPJQXEKOKHSMHORHZAHPSHUDHOZHDIHHOGGVOZUHUBHUSGMHUSWHUVHUFUBDHYAHYCHYDHKBMMLRPXSRDSRGWHRHFAIWLKARICNIACITCIDGIFLRDEIJMIKKIKNBLUXGGIPAIPMLVBISDFDFIBECSQIBSIBRIBTIWDIBXIBCAKIIBLBBLYYYIPRICAICDIUSCICICJICEICGRACFRCIFMIKRCIOILVIDLIARILPILLIMRITXIMGIMTIDEIDPIOAIGOIILIFCIDRIBUAXCIDAAWQIAAIPNITNFFIINSIVAINCICCINTINLXRAITWINXIICIINCARNTTTCUITAUGLIMAITSILNNTEIVTIWYICTICPIFTIJTRFLIFFIGNISNAIJIHEIJWITKIAKEXXNCCIAXIBYICSICXREDIIGIFXIJAHSPTHNRSQISFITHIPTIKYISKFWAITUINVINDIRAIRCIRBIRGIAWBISIRLRDKXMRMZAKCEISIILFXYZISASOYDQAIOMSDYMTPILCIAJICBISWIGSISVIOSIAIIAFISRISTITYACLIAMIEIGCIMMIIFSIKAIVSIVWIJEOICIXRIZMIZAJTNJGJJNYJKRJWDJCBRFXJEXJAZJDAJDPJHMTQMJMCJSJJESJCKJAEJAWJMBWWWFJXJAKJAXJACJSVJALJFLJAAJTAJATJAPJTYJZRJJAXLDJPNJEAJSIJAIJTXPJSBZFJASJCFJCTJCXDWWJEDJEIRZACFTJGDMJLJEKHTLJTLJNRJRNJDIJSAJSMVTBJSSJTFJTCJTTOPSJSHEXSJFUOSWJBUJMGJMKJAFJAGJCSQNZUEJJCCJXAJEFJFAJICJLXJNLJNVJPOMDJJRIJEJJEPJSEJGOJSTJJPJKTJXTRSPJPQJECJTDJWYJXXJIBJSWHKNRASJNAJDGJBRJHNJONJMJJMMJMTODIJAVJCIJVKENZJNJJSXJURJFSJUCJUBDKEJSYMEYDOJJIAKTAKSAKCRKHKKGZKDCKMIKLSKNIKLCKLHKLMQNKKMCKAICKSKFSKIIKESKMFKMPKIZKHEKSUKRBKLGKAJKAEKTVKTKKATMVDXKAKRNKAWKAOKPHKKAKZSKCHJFKKLXFKLKFAKDAKENKBAKAHKQAKVSKEYLYMFTPKEEKZWWKHKHRKHPKRVKHOKHYUAKKNGBEZKFRKNXKASKIPKNSIRKKHAKHCKIAKRAKNAKHXKGTKOAOYEKGLKOMKMAKMVKOBKALKMGKSMKOSWOKKJCKFCKRGKROKRIKYMOPCKILKPAKZAKBVKACKZUQVRKWNKTCKGADAMKGBKEWLZFLHBLLDLGALGCLTYLWLLAXLWALAHLJYLRBPHOLEXFNTLABLRCLDEBNXLNCDSMTAMLCOLANLNELXPLAPLPELSAAPTLCBLOTJKALTELTOLTUJFCLUKLVTSKQLALJEVHCALKLLKRLBHLMRTCRPAPLKNLZALZTLAOLKALLLLXWLPNLRDOTNLTCLAFLDALDMLDILSULARLAYLPLLAQLATLADLEBLCALIALGDLWDLENLORLELLVLLYWLAALCRLIQLTALCGLKDLMEGCBGDQLRTLSYNOTLMCLNPNEGLERLSETUYALRLCDLCNLCMEDDFEDLMNLIJUMALECSMSLAMLAWWGTLNILEULYFLRALVGLLBLNAXLGLACXDDCBDLNGLOGCLVLMSLCYLNXLOVLHCLSSORALHALGTCDCLRRLSCTASLTWLKELUTLVDGECCLHLHTLTFLTRLHSUNYLGLLXALUVLFELXOLUZUKWLYDLCHLYCLWGDATLXFSSXLYXAZNLPRLAULYBMMHHOGMTSMSFMXSMHFMRKMWMMSJMWIMYPMAVMLVMMJMXFMXDMJCPLGDZRMSNMFBJNHMCFMRGMPJTFGMAAMAKMCCMGAJLAMGLMNCMKAMNBMCVMAQMCNMTDMCKMCSMDHDANMJBMGRMLHIRMMZSMATMAJAKMMLGMLXMKKMASMLTMAEMTZMLCMLSLODSCWMAYMWSMAHMLBMDLMDAMNOMHNMTOMNRMANMNXMADMARMCPMGIMKOMRWMCEMSLXMAMBEMPHMRAMFAMVNTRPMTHMSYMSWMPLLMJMIAMNVMRFMWYMDEMVRMVLMAIMAXMXLMXUMXJMXPMYDMYIMBSMCHMKLDACMDSMEKMDMMRZMCLMDFMDYMEJMGKMELMKNMNJMXXMECPOVMRDMHLDSLMEMISSMEIMNAASHMESMSQMETMERMVIMEXMTRMTJPIXMPSMXBMJTMXCMXAMXTHURBSKOWLMPTBIBWIZNYLMPAMJRMEAMIDMFRMISMDWFAXMEPMWANITMWTHTEMLRMABRJMMLKDLKMFSOXOMIMNABOMREBEMAZMNLMNSWDGLIRMICMIRMIFMOSMAFMRNBDGMVAMSAMJFMBOMXEMFZMOWMULMLEMDVMVGRRVMONMNHMFCMDBMTIMKYMGXMNTMNYMALMSSMROGAIMPIMSINZMMTNMTCPKPBRRMBIMHAMPCMTVMDNMTXWBRMFTMNZMUAMMRMAWMYMMYWMYTUBAMMAMYAVKGMHVMTUNIASIQNEJNHVNHCDMDNINFEYNUBNJAROWNLGNHGWARANLNHZNAHNKLMRENDFCNJACKNYANAPNCMNASNJCNCONTKNSRRFINANNCNROKNALNCRNAENIHKUSLFIGTYTNCNXTGRDJTEANDNJSNOLNLSNTWNWZEVMNRRNRKNVCNAVNVPNAYIRINVMNVLXNVXNSNZANEBNECNCGNFTNLANLCCGERNANOSTOXNSLNMAEJANETNEZNEANHTNWDNYHGRYKRCHVANLTNTJNXFNXSNISNGANGRNGXEXTNLYNKVNSANLWNBSNCANVKNOHAKGNBLNOKNCTNRLNMDOMDNOCNEFAULNESNRDTYANDSNWSNRTNCFFNANOAHMFNRXNBTUBTNIRNORDOCRTVNAINAOHMRNAJNATNFCNBNNCBNFANRCSBXNRVNWWPTONENVBGNWLNLLNFLNSFNCENEENPXNEWNACNDACMUNEXNICNTXRVFNTAKOENSSNHLNWENWANWRNWTPLRNWNNAMIBKNOZNAANLHNSZTFNXNTLBTNOVPTRNVRNVQNVGNSPNBENPONOYNHRNUNNYSNJEORNONSFETOCMDRLOWEOHKBCNVCXOCSTUKODSFOCGBOOKJOKPOKAOKLOLXKVKOLTOALOLYOMAORFOMSOAVOAEONIOMFORLOTGOTMMEDOHYOPAOSABOSORROLEOTPOPVLLOOAXORDORJOREORXORKBUEORMORBOMLOVVOTROEANGKOACOGNOEDOIXKOVRNGOADJPAOSHOCOODYFNLRONOOTOLAOAROXEWDKOAAOZROZJOSUORTPVLGAPPIPHRSPXTBPHPFYPXRPNCPMIKTLPCRPNRPBAPDQXASPDGPUAPMTPRPKSTWISPCEPABPRCPAQPXPPICPAKPCVPCXPBNPQAPCOPECPFAPINPSAPCJPPMPARNMIPFRRCYPAEPKWPIAPKRPPCPNAPTPPNWJSPPIRPFNODMPAXXPAPAAPEAPHTPMAPNFPGIRSLPEIPVIPNHPHUPNMPAHAFDPTNHMPPAIPDIPGXPGFPRRPMWPTAAPEIREPRAPSTPSCPTBPTCBYTETLPHEIRPKGCPRLPBYHPAPVUPXAPGTHAKPDFPEXPASPEMPDYPENPNEPCACVTPCCPAGPGPPPQPVNFPRINPPEOPMXPHMPHCPTKPTYPHVPMYPALPHIBCHPDDPHLPHBKZMPHAPHNPAMPPGPHYPHGXPXVAPPDTPCHPLUMKSPNPPIMPCLFLGPIOPERPRNPLNPMSPLZPYZPSFPBDPOCPDAPAZRMIPAWPTSPACPMOPSRPOTPOFPLCPLFPNYNRWPPHPIKSRPPBWEDLPBBPHHPMVPHSHBTCUKPLAPAOPLBPNDPSIPLXPTQPORPGAAFPPOAPONPDCPSNPWLPFSPWCPRFPREBATPGLPMEEMIPMUBFAONMPSDAUHPRDPWAPMMWCPPMCCRYPRMPKZPJPPCNPRYPATBCKPTIPJEPJAPWFPVGPRHPSZGIYPADPFZPTTPROPPAPTHPTLAWDSPRPRVPSWUDAPSPPUVPNGTXVPGHPLYPTVMGOPYRPLKPRWFQAQQEQNTQFAQLKQACQTRQAFQSMQDAQTXQUEQNALBQQAJQAHQASQAQQCCQWAQWLRBBGBRBKHCFNCOHCBYCWLKINLEELCSLOPLOSMRHNWOSMZSTNSMGTOFVYTVLLWADWITMTLWESRJTRAJRKMRFAREXRMTPPKRGMMWRRAQCSMRVRRVNREIRYTRTNRCJKSSRCBCDTRCDVCBRLVRebusRIXPSHRBNDEVRDVRSVSTRRHCVRDRAVREFREKRVVRBHRGYRAHRGERAGRAETSHRILREWREGRGLRXAJJMREPCEARELRLIRTSRANROARGSRPARPHRBCRSTRUTRGVRDSRIURIARVCRICRCAWHHHPRRLERIDRAKRAZPOLRIMSKAREOGRNRIORVMRGPUNRRXIRDLRBTRBYROXRKWROCRMALIFRDZFADRRZRRLBTUROFRMVRNSRORKRSRNBNRGRFSRSSROSSDMRALRARRTRRKTJCRROVVOSRCGRFRMJNACWRRRRRFSHFRAXRAMRYLRPKRLMASYRXPRYBRBAKDRRGAROJRJARJZRCTRKHRMFNVYNRNNAFKIWNOWROPPPWRRARSFRYSRSNHRHRWERSBRLHRMGRURKLECGIRUHRLUMIGRFFESLRUZRUCRNDRUARWARWDRWLRYARYNRYRRUKRYZRAAREVBUGOMNSENSGCSIXQSRKBNCBNIBGBZQBVVSJMSXTTGWSJOSBDMYXTVSTVLTVPTVQLSVFUFVGOSAQSMURBRSVBMHQSYHKYEKPMSWUSHAAWUBDSSZBBECRZOSAAKYDSABSKVSACSAGSAHSAISAMSANSAOANXSASSAVSAWSAXSAYSAZSBASGUSBBTUXSBFSBGSBISBLSBMSBOSBQSBRSBSSBUURJSDGSJXSBZAMESCASCCSQHSCESCFSCISCKSCLSCBSCNAHISCPSCQSICSCRSCSSCTSCVSCXSDASDBSDCSDDSDESDFSDHSDKSDLSDNSDUSDVSDXSDZSEASEDSEESEHSEJSELSEOSEQSESSETSEVSFASFCSFESFFSFGSFJSFLSFNSFPSFRSFSSFTSFUSFXSGBSGDSGFSGHSGISGKSGMSGNSGPSGSSGTSGXSGYSHBSHCSHDSHESHGSHJSHKSHLSHMSHNSHOSHPSHQSHRSHSSHUSATSHVSHWSHXSHYSIASIBSIESIHSIJSILSIMSIOSIRSISSITSIVSIWSJASJCSJESJJSJLSJTSJYSMYALCSPSSPTSPUSPVSPWSPXSQASQCSQFSQLSRASRCSRHSRKSRLSRNSROSRQSRSSRUSRWSRXSRZSSBSSCSSDSSESSFSSGBBBSSKSSOSSPSSQSSRSSSSSTSSUSSVSSWSSYSSZSTASTBSTCSTDSTESTFSTGSTHSTISTJSTLSTOSTQSTUSUUSTVSTWSTXSTYSUASUBSUDSUFFDYSUGSUHSUISUKSUMSURSUSSUTURFSUVSVASVDSVFAWJSVHSVISVJSVLSVNSVOSVSSVTSVXSWASWBSWCSWDSWESWGSWISWJSWOSWPSWQSWRSWSSWTSWVSWWSWXWSWSWYSWZSXASXCSXESXMSXSSXXSXYSYASYCSYESYFSYGSYISYJSYKSYNSYRSYSSYVSYXAZQAZGSYYSZTBHVBLYBNCBRZRBGCDGCDSCEECFLCGLCIGCNKCNOCQHCSCCSHCSYCSZDKTDKYDNIEABEANENRESKEXLEXYFFDFFHFJEFLHGADGDEGDGGIKGNAGSWGXLHAUHIPHJEHKAHLOSJBHRIHSKHSVHSYIGAIJSILSINKIRVIRZJAMJCMJIMJKKKKSKOPKSPKYRLGULLALLSLMGLMOLRSLSPMCGMDTMLOMMSMRIMRRMSGMSPMTGAPDSBWNADNAZNCSNKSNONNRZNSCNSENTBNTGOKSOKTOLCOLOONGOSLOSSOTLVOZPIVPLTPMRPNSPOBPSVPTMPURPZRRBWREJRERRFTRGCRLSRMPRSESKBSKCSKDSKESKFSKGSKISKKSKLSKNSKOSKRSKSBBRSKTSKUSKWSKXSKYSKZSLASLBSLDSLESLFSLGSLHAGESLKSLLSLMSLNSLPSLSSLVSLWSLXSLYSLZSMASMCSMDSMESMFSMHSMKSMLSMQSMRSMTAOSSNASNBSNESNFSNHSNISNJSNKSNLSNMSNPSNQSNSSNTSNUSNVSNWSNXSOBSOCSOHSOISOLSOMSONSOOSOPSORSOTSOUSOVSOWSOXSOZSPASPBSPCSPESPFSPGSPHSPISPLSPNSPPSPQTBSSVVTGTTHBTIHTRLTRNTTMTZUUGPUKUUNTUSKUSNUZSVDOVGSVRBVRSVSVVXNTWYWCCWFCWLKXLKXMXXPGXSAXSNXTAXTRXXSYBESXNCSSSAFKFESQPLLCLLPLLILLXALKSRRHCWTLKUFACDLSXDRZTOWOSYDTAIRFTBITBMTHOTCVTDCTESHETTSDSBTFPGTGMVIPTAGFBOTWITINTFBTJKTZKTKEJELTALTFFTAETMITPATNRTDMHTOTAPUTMTPSTQNTHCTPLIRRTTHROTRMSCTPTMNDTHPGSTVRTQETXLTXMTUOXNRTDVTRFVRCTXRTPRTXOTNETPFTMHTYFTFYVNZRRYTCDTIMTLWTEMTEFTBNTHRTCMTLXTELTDEDOTTEHTMSTNLTEBTNGTENTETTERTISTXZTXATXTTXSCWTTXNTEZTGCTCGAIQTAXTHATSLTFHTFTTHGTHJTLMTPVTHDTSXTVJGFNLEGLCCTCWTCXIHSTHUTBDBLIGCRTNMTBATIKTJNTGGTTWMOHTKCTMRTIETVIAWCTYJTSRTLSTMMTAYNTRTBXTOBTOJTOLTMKTOPCHETLYLKWTPDTTLTOTTHETHFTOYTGETVHTDRGPDTDXTWLJCHTDOTRGHBATMQTMXTRRMUITRCTWWTNBRTMCLRTVATPUTRTSRTTLLTCCTCNTRJTGYTHZTIABAPTRDSWLTMATMTTNWTNTRECSBJTSMLOFTWARBDTSOTNFTFKTSATGXTNITSNTSGKTSGJBTWMUTTTNAAUCVENTVFTRAKTBTXCFNVTVOTIWTCETCHTCTTCPTEPTFATXEKCATLATMDTRZTNURMYTNVTPPPCWTPMTNPTRMTLFTGOTFITQRMCTTPNTTRTSITCBTADTZETTSMGMTMZEARTPTMPOBOLTDITPXTMYTFODCLTSPMXQTANELVTPGTGISRFRRTSEITAUTPZTMLTPYTTCUTNTWETRWTSWTSTTSJTSKTICTMCTLVTDATNXTRUTGNTMGTBHTIBTTPTSYTRYTSSDRCTSVTOSTROTBGTKXTCATYGTDSPSSTTATBRTOMTUITFLBLXTLPTULTUZTARTAJURNTBCTACTRQTUCTHKTHSHVKTHYTRKTUATLTUSBTWBTWOTCYTJTTNYTWJTYWTYRTJSTUMTKKUEUUCGCUHDODDOICNVEXMGIHGKAGWYUIAUABUALUACUCSUEAUFSCFUKRFKRHSDSTQFCGXAGRUADUAJUAAUASHBUHLEJUSLEAMSHNDURAUSAUSVRTRBUAFUAIUCCUCHUCOUESUGDUGCUHLUHSUJRUJTUKIUKLUKMUKNUKPUKSULTULHULRUNCUNFUNJUNSUNUUPLUPSURVUBGUSFUSHUSJUSXUTAUTRUTSUTUUVAUVGUVMUVNUZBAUIWECQIDUITUNOVNLVAGVARVVVVILVBAWIWVBDVACRDWVLAVLNEHRVLUVJAVAAVGCVGDVRHVFCWGAWELVTXBTPVALGRVHVNTMBKWAMOVMVYENVVCTSSIFXFPAVPRXVATVCAVCMVOIVDAVEAVECVEEVEIVJCVESVEXVFTVGNVGVVHAVHMVIBVICVIEVIFVIGVIHVIKVINVIRVJMVJTVVMVLEVLGVLKVLOVLTVMAVNKVOAVOGVQIVPBVPVVRAVRLVRNVVCVSBVSNVSOVSPVSSVTCVTHVOEVTKVTLVTVVURVUSVZLVLMWCYWEVWLGVTIWDLWRRXWSCGGGOTWPTWAVATXWSGWTCWEBTDBWLCBLWWCBWTFWSFWACWLXSWNWCWWCRYWZWCGWCATEEWEWWJAWAAWSCPCMBLKWSTNPCWAEWALWTVWGNKMRWPAWSLWSAWHEWTPWWDWHTWEAWRAWWLWIFWIGWHSWFOWGPWDAWNAJETWSIQGAWIAWONWATWAWWOLWEXWLBWINWAGWSMWVLWZZWMTWUKWNRCWYWOAXWWWWMWWSWWIWRTWRFCWUWYCWYGWANWENXJEXABXAEXJCXERXRCCXACXJXJTSEUXOJXPSXARDGAAKYYAKLLMCYGAYGYZRLYHMHDEMJELWIYEERVNYTYFSAYUAYEUGNUMKBZEAZJAZRCITEMREZDGZQIMXIZGJTUKVZKZHMBGMLUMZEORZPZYRZRRZUSYZZAIZARZAVZAWZMARZVMBNZANZASCJGCFZCYNWZPTZPOOM

In [17]:
df_airlines.head()

,IATA,ICAO,Airline,Telephony Designator,Country/Region,Comments
0,PR,BOI,2GO,ABAIR,Philippines,NaN
1,NaN,EVY,"34 Squadron, Royal Australian Air Force",Multiple,NaN,NaN
2,NaN,GNL,135 Airways,GENERAL,United States,NaN
3,1A,NaN,Amadeus IT Group S.A.,NaN,Global,GDS and airline hosting system (CRS/PSS)
4,1B,NaN,Sabre travel network Asia-Pacific (ex-Abacus),NaN,APAC,Regional distribution

# Airport

In [32]:
import requests

airport_url = "https://en.wikipedia.org/wiki/List_of_international_airports_by_country"

headers = {"User-Agent": "airport-codes-scraper/0.1 (your@email.com)"}
airport_resp = requests.get(airport_url, headers=headers, timeout=30)
airport_resp.raise_for_status()

In [33]:
from io import StringIO
import pandas as pd

tables = pd.read_html(StringIO(resp.text))
print(len(tables))

230

In [29]:
df_airports = tables[1]

df_airports.head()

  Location                      Airport IATA Code
0  Algiers    Houari Boumediene Airport       ALG
1   Annaba          Rabah Bitat Airport       AAE
2    Batna                Batna Airport       BLJ
3   Béjaïa              Soummam Airport       BJA
4    Chlef  Chlef International Airport       CFK

In [ ]:
from bs4 import BeautifulSoup
from io import StringIO
import pandas as pd

soup = BeautifulSoup(airport_resp.text, "lxml")

frames = []

for table in soup.select("table.wikitable"):
    df = pd.read_html(StringIO(str(table)))[0]

    df["country"] = table.find_previous(["h3", "h4"]).get_text(strip=True)
    df["continent"] = table.find_previous("h2").get_text(strip=True)

    frames.append(df)

df_airports = pd.concat(frames, ignore_index=True)

In [56]:
df_airports.head(4)

,Location,Airport,IATA Code,country,region,continent,Passenger Role,Provinces/Territories,State,ICAO Code,State/Union Territory
0,Algiers,Houari Boumediene Airport,ALG,Algeria,Northern Africa,Africa,NaN,NaN,NaN,NaN,NaN
1,Annaba,Rabah Bitat Airport,AAE,Algeria,Northern Africa,Africa,NaN,NaN,NaN,NaN,NaN
2,Batna,Batna Airport,BLJ,Algeria,Northern Africa,Africa,NaN,NaN,NaN,NaN,NaN
3,Béjaïa,Soummam Airport,BJA,Algeria,Northern Africa,Africa,NaN,NaN,NaN,NaN,NaN

In [52]:
df_airports["IATA Code"].isna().sum()

np.int64(1)

In [60]:

df_airports_new = df_airports[["Location", "Airport", "IATA Code", "ICAO Code", "country", "region", "continent"]]

In [61]:
df_airports_new.head(500)

,Location,Airport,IATA Code,ICAO Code,country,region,continent
0,Algiers,Houari Boumediene Airport,ALG,NaN,Algeria,Northern Africa,Africa
1,Annaba,Rabah Bitat Airport,AAE,NaN,Algeria,Northern Africa,Africa
2,Batna,Batna Airport,BLJ,NaN,Algeria,Northern Africa,Africa
3,Béjaïa,Soummam Airport,BJA,NaN,Algeria,Northern Africa,Africa
4,Chlef,Chlef International Airport,CFK,NaN,Algeria,Northern Africa,Africa
...,...,...,...,...,...,...,...
495,Mendoza,Governor Francisco Gabrielli International Air...,MDZ,NaN,Argentina,Argentina,Americas
496,Neuquén,Presidente Perón International Airport,NQN,NaN,Argentina,Argentina,Americas
497,Posadas,Libertador General José de San Martín Airport,PSS,NaN,Argentina,Argentina,Americas
498,Puerto Iguazú,Cataratas del Iguazú International Airport,IGR,NaN,Argentina,Argentina,Americas
499,Resistencia,Resistencia International Airport,RES,NaN,Argentina,Argentina,Americas